name: docker-auto
# runs every at 6:50 AM
# the image should be updated before the interop schedule every day at 8AM
on:
  schedule:
    - cron: '50 6 * * 1-5'
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: haproxytech/haproxy-qns
    steps:
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
