name: docker-auto
on:
  schedule:
    - cron: '10 9 * * 1-5'
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: haproxytech/haproxy-qns
    steps:
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
